cgview:
  settings:
    ruler:
      font: 'sans-serif, plain, 10'
      fontColor: 'black'
    backbone:
      color: 'grey'
      thickness: 5
    dividers:
      slot:
        show: true
        thickness: 1
        color: 'black'
  sequence:
    font: 'san-serif, plain, 10'
    color: 'black'
  featureTypes:
    - name: 'CDS'
      decoration: 'arrow'
    - name: 'tRNA'
      decoration: 'arrow'
    - name: 'rRNA'
      decoration: 'arrow'
    - name: 'blast'
      decoration: 'arc'
    - name: 'codon'
      decoration: 'arc'
    - name: 'DEFAULT'
      decoration: 'arrow'
  captions:
    - id: "title"
      position: "lower-center"
      backgroundColor: "rgba(255,255,255,0.4)"
      font: "sans-serif, plain, 24"
  legend:
    position: 'upper-right'
    alignment: 'left'
    fontColor: 'black'
    backgroundColor: 'rgba(255,255,255,0.75)'
    font: 'sans-serif, plain, 14'
    default: 'Other'
    items:
      - text: 'CDS'
        swatchColor: 'rgba(0,0,153,0.5)'
      - text: 'tRNA'
        swatchColor: 'rgba(153,0,153,0.5)'
      - text: 'rRNA'
        swatchColor: 'rgba(0,153,53,0.5)'
      - text: 'Other'
        swatchColor: 'rgba(153,153,153,0.5)'
  layout:
    tracks:
      - name: 'CG Content'
        position: 'inside'
        contents:
          plot:
            sequence: 'gc_content'



